replicaCount: 1
image:
  repository: solomonai/affine-graphql
  pullPolicy: Always
  tag: stable

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
# map to NODE_ENV environment variable
env: 'production'
app:
  # AFFINE_SERVER_SUB_PATH
  path: ''
  # AFFINE_SERVER_HOST
  host: '0.0.0.0'
  https: true
serviceAccount:
  create: true
  annotations: {}
  name: 'affine-renderer'

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

probe:
  initialDelaySeconds: 20

nodeSelector: {}
tolerations: []
affinity: {}
