name: 'Deploy to Cluster'
description: 'Deploy Solomon AI Workspace to cluster'
inputs:
  build-type:
    description: 'Align with App build type, canary|beta|stable|internal'
    default: 'canary'
  cluster-name:
    description: 'Cluster name'
    default: 'production'

runs:
  using: 'composite'
  steps:
  - name: Setup Git short hash
    shell: bash
    run: |
      echo "GIT_SHORT_HASH=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"
  - name: 'Auth to cluster'
    uses: './.github/actions/cluster-auth'
    with:
      cluster-name: '${{ inputs.cluster-name }}'

  - name: Deploy
    shell: bash
    run: node ./.github/actions/deploy/deploy.mjs
    env:
      BUILD_TYPE: '${{ inputs.build-type }}'
