replicaCount: 1

image:
  repository: solomonai/affine-front
  pullPolicy: Always
  tag: "stable"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "affine-web"

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

probe:
  initialDelaySeconds: 1
