name: 'Auth to Cluster'
description: 'Auth to the DigitalOcean Cluster'
inputs:
  # gcp-project-number:
  #   description: 'GCP project number'
  #   required: true
  # gcp-project-id:
  #   description: 'GCP project id'
  #   required: true
  # service-account:
  #   description: 'Service account'
  cluster-name:
    description: 'Cluster name'
  # cluster-location:
  #   description: 'Cluster location'

runs:
  using: 'composite'
  steps:
  # - id: auth
  #   uses: google-github-actions/auth@v2
  #   with:
  #     workload_identity_provider: 'projects/${{ inputs.gcp-project-number }}/locations/global/workloadIdentityPools/github-actions/providers/github-actions-helm-deploy'
  #     service_account: '${{ inputs.service-account }}'
  #     token_format: 'access_token'
  #     project_id: '${{ inputs.gcp-project-id }}'
  - name: Install doctl
    uses: digitalocean/action-doctl@v2
    with:
      token: ${{ secrets.DIGITALOCEAN_TOKEN }}
  - name: Save kubeconfig
    shell: bash
    run: |
      doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ inputs.cluster-name }}
  # - name: 'Setup gcloud cli'
  #   uses: 'google-github-actions/setup-gcloud@v2'
  #   with:
  #     install_components: 'gke-gcloud-auth-plugin'

  # - id: get-gke-credentials
  #   shell: bash
  #   run: |
  #     gcloud container clusters get-credentials ${{ inputs.cluster-name }} --region ${{ inputs.cluster-location }} --project ${{ inputs.gcp-project-id }}
