name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - canary
    paths:
      - tools/workers/**
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy'
        type: choice
        default: stable
        options:
          - stable
          - staging
          - development
          - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        uses: cloudflare/wrangler-action@v3.12.1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: 'tools/workers'
          packageManager: 'yarn'
          environment: ${{ inputs.environment }}
