replicaCount: 1
image:
  repository: solomonai/affine-graphql
  pullPolicy: Always
  tag: stable

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
# map to NODE_ENV environment variable
env: 'production'
app:
  experimental:
    enableJwstCodec: true
  # AFFINE_SERVER_SUB_PATH
  path: ''
  # AFFINE_SERVER_HOST
  host: '0.0.0.0'
  https: true
  doc:
    mergeInterval: "3000"
  captcha:
    enabled: false
    secretName: captcha
    turnstile:
      secret: ''
  copilot:
    enabled: false
    secretName: copilot
    openai:
      key: ''
  oauth:
    google:
      enabled: false
      secretName: oauth-google
      clientId: ''
      clientSecret: ''
    github:
      enabled: false
      secretName: oauth-github
      clientId: ''
      clientSecret: ''
  mailer:
    secretName: 'mailer'
    host: 'smtp.resend.com'
    port: '465'
    user: 'resend'
    password: ''
    sender: 'noreply@inbox.solomon-ai.app'
  metrics:
    enabled: false
    secretName: 'metrics'
    customerIo:
      token: ''
  payment:
    stripe:
      secretName: 'stripe'
      apiKey: ''
      webhookKey: ''
  features:
    earlyAccessPreview: false
    syncClientVersionCheck: false

serviceAccount:
  create: true
  annotations: {}
  name: 'affine-graphql'

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

probe:
  initialDelaySeconds: 20

nodeSelector: {}
tolerations: []
affinity: {}
